// $('.sec-2')
// .addClass('social')
// .css('backgroundColor', 'white' )
// .css('height', '100px')
// .css('width', '100px')
// .css('margin', '5em auto')
// .css('padding-top', '1em')
// .css('display','flex')
// .fadeIn()
// .html('Hello')
// .delay(2000)
// .fadeOut();